#
# Makefile for the Xiaomi touchscreen drivers.
#

ifeq ($(or $(CONFIG_MACH_XIAOMI_DAISY),$(CONFIG_MACH_XIAOMI_SAKURA)),y)
    obj-y += daisy-sakura/
endif

obj-$(CONFIG_MACH_XIAOMI_VINCE)		+= vince/
